### ISSUE TITLE
Accept also files with extension .yml as possible YAML file

### ISSUE THREAD

**Issue by obfischer** [jQAssistant/jqa-yaml-plugin#1]
Currently we accept only files with the extension `.yaml` als possible YAML document. As Maven with the Maven Polyglot Extension supports YAML as POM format and the containing file is called `pom.yml`, we should consider to accept also files with the extension `.yml` as YAML file.

**Comment by DirkMahler** [comment]
Implemented in https://github.com/buschmais/jqa-yaml-plugin/commit/fde67d7f4e8c41db7d488addd734f56b7c90f2c1
